=== FeiCoding/XML_Practice/Project2/dtd/Ass.dtd
<!--The DTD file has a top element whiskies, which means there will be lots of individual whisky elements-->
<!--Each whisky element has three main parts, which are introduction, body and tasting notes.                      -->
<!--The data type of whisky is required, in my projects, they are all "Scotch".                                                         -->

<!ELEMENT whiskies  (whisky+)>
<!ELEMENT whisky  (introduction, body, notes)>
<!ATTLIST whisky types CDATA #REQUIRED >

<!--In introduction, there are title part and intro part.                                                                           -->
<!--The title includes whisky brand, region, town or village, website, openingtime and image -->

<!ELEMENT introduction (title, intro)  >
<!ELEMENT title (brand, region,  town, website, openingtime, image)  >
<!ELEMENT brand (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT town (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ATTLIST website target CDATA #REQUIRED >
<!ELEMENT openingtime (#PCDATA)>

<!ELEMENT image (caption?) >
<!ATTLIST image   filename CDATA #IMPLIED
                                 src CDATA   #IMPLIED
                                 alt    CDATA    #IMPLIED>
<!ELEMENT caption (#PCDATA) >

<!--While intro is a paragraph of some information about the brand, which possibly mention the year established     -->

<!ELEMENT intro (para)>
<!ELEMENT para (#PCDATA| year_established )*>
<!ELEMENT year_established (#PCDATA)>


<!--The body part contains many paragraphs -->

<!ELEMENT body (p+) >
<!ELEMENT p (#PCDATA| year_established | oak_used)*>
<!ELEMENT oak_used (#PCDATA)>

<!--The tasting notes include new make whiskies and some vintages.-->
<!--In new make, the notes are simple, only have nose, palate, and finish-->
<!--I assign the types including flavour, feeling and last. Within each type I defined each character which appears which makes each type more specific. -->

<!ELEMENT notes (new_make, vintage+)>
<!ELEMENT new_make (nose+, palate+, finish+) >
<!ELEMENT nose (#PCDATA)>
<!ATTLIST nose type CDATA #IMPLIED
                               colour CDATA #IMPLIED
                              flavour CDATA #IMPLIED
                              feeling CDATA #IMPLIED>

<!ELEMENT palate (#PCDATA)>
<!ATTLIST palate  type CDATA #IMPLIED 
                                 flavour CDATA #IMPLIED
                                 feeling CDATA #IMPLIED>
                               
<!ELEMENT finish (#PCDATA)>
<!ATTLIST finish  type CDATA #IMPLIED
                                last CDATA #IMPLIED
                                flavour CDATA #IMPLIED
                                feeling CDATA #IMPLIED>

<!--Vintage notes would include more information than new make.-->
<!--Vintage may named based on the year or be given a specific name, sometimes with oak speecified, and alcohol level.-->
<!--The nose, palate and finish are the same as the new makes.-->
<!--It also has conclusion, the flavour camp suggested, and where next  suggest the similar whiskies -->

<!ELEMENT vintage (year?, name?, oak?, abv, nose+, palate+, finish+, conclusion, flavourcamp*, wherenext?) >
<!ELEMENT year (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT oak (#PCDATA)>
<!ATTLIST oak  type CDATA #IMPLIED >
<!ELEMENT abv (#PCDATA)>                             
<!ELEMENT conclusion (#PCDATA)>
<!ELEMENT flavourcamp (#PCDATA)>
<!ATTLIST flavourcamp  type CDATA #IMPLIED >
<!ELEMENT wherenext (#PCDATA)>

=== FeiCoding/XML_Practice/Project2/xml/whisky2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xslt/ass2.xsl"?>
<!DOCTYPE whiskies SYSTEM "../dtd/Ass.dtd">
<whiskies>
<whisky types="scotch">
    <introduction>
        <title> 
            <brand>The macallan</brand>
            <region>Speyside</region>
            <town>Craigellachie</town>
            <website target="https://www.themacallan.com">www.themacallan.com</website>
            <openingtime>open all year easter-sept, Mon-Sat; Oct-Easter, Mon-Fri</openingtime>
            <image filename="Maccallan18yo.jpg" src="../images/Maccallan18yo.jpg"></image>
        </title> 
      
        
        <intro>
            <para>In the early days of single malt being commercialized,
                it was common practice to compare the drinks to another wood-aged spirit
                with a high reputation. "This is as good as Cognac," marketeers would say. 
                In The Macallan's case they'd add terms like "first growth", which is apposite. 
                The Macallan's HQ, the whitewashed baronial Easter Elchies House, 
                dose give the whole estate a somewhat refined, chateau-like air.</para>
        </intro>
    </introduction>
   
    <body>
        <p>Although The Macallan's approach to whisky-making links it directly with the older distilleries in this cluster,
            and adds weight to the theory that the earliest ones(the distillery was founded in
            <year_established>1824</year_established>)
            tend to make the heaviest whiskies, the manner in which it has sold its whisky has always seen it exist slightly 
            off-centre from the rest of the industry. One suspects that it doesn't mind that much.</p>
        
        <p>This connection with the old ways is manifested most clearly in the stillhouse
            (or at the time of writing, stillhouses; a second one was brought on-stream in 2008), 
            where tiny spirit stills hunker over their condensers like Nibelungen dwarves.</p>
        
        <p>Reflux is a bad word here. The emphasis is on producing a spirit with guts. 
            The new make, which you can taste as one of the 
            many strokes of genius on its innovative tour - is oily, malty, and deep, but importantly, sweet. 
            It's opinionated, making it clear from day one that thais is not a spirit that will be pushed around.</p>
        
        <p>That weight is vital as The Macallan has always allied itself with ex-sherry casks. Such is the symbiotic relationship 
            with sherry that owner Edrington has casks made to its exacting specifications by the Tevasa cooperage in Jerez.</p>
        
        <p><oak_used>As has been traditional, a mix of European oak(Quercus robur), with its high tannin and aromas of clove and dried fruit,
            and American(Quercus alba), all vanilla and coconut, is used, giving whisky maker Bob Dalgarno two very different main streams
            of flavour with which to work and there are many variations within those two.</oak_used></p>
        
        <p><oak_used>In sherry casks, the oiliness of the new make is both a facilitator of the flavours seeping from the oak, and a barrier to
            aggressive tannins, preventing them from grabbing the palate like a ferret with a rabbit. Old Macallan is smooth, not grippy.
            American oak(seen also in some ex-bourbon) reveals more of the cereal and soft fruity notes.</oak_used></p>
        
        <p>When I was speaking to him for the first edition, Dalgarno was putting together a vatting of sherry oak 12-year-old from 
            a range of whiskies, each with a different hue. His deep understanding of how there is a correlation between a colour and 
            a flavour spectrum has now borne fruit in the newest Macallan range: the four-strong 1824 Series.</p>
        
        <p>This was his solution to an issue facing most producers: tightness of stock. Scotch's rapid expansion in the early part of the 
            twenty-first century caught distillers on the hop. Memories of the whisky loch of the 1980s and subsequent distillery 
            closures had meant that industry production levels remained cautions for decades. The inevitable result was a shortage of 
            mature stock when the market exploded. The solution? No Age Statement(NAS) whiskies, which free the whiskymaker from the often
            restrictive nature of age statements, allowing them to explore flavour and distillery character.</p>
        
        <p>Dalgarno's response was to look at how colour could be used as an indicator of character. The irony
            (not lost on the firm's accountants, you feel) is that the new range is more expensive to produce than the 
            whiskies its members have replaced.</p>
        
        <p>It is unlikely that the stock shortage will reoccur. Huge aircraft-hanger-sized warehouses have been built and 
            a new much-expanded distillery is currently being constructed.</p>
        
        <p>Meanwhile, The Macallan straddles the world, for many the epitome of whisky as luxury, for others a manifestation of 
            old-style single malt, with a modern twist.</p>
        
        
    </body>
    <notes>
        <new_make>
            <nose type="colour" colour="clean">Clean</nose>
            <nose type="flavour" flavour="green fruits">green fruits</nose>
            <nose type="flavour" flavour="sulphur"> Light sulphur</nose>
            <nose type="feeling" feeling="fat">fat</nose>
            <nose type="feeling" feeling="oily">oily</nose>
            <nose type="feeling" feeling="malty">malty</nose>
            <palate type="feeling" feeling="fat">Fat</palate>
            <palate type="feeling" feeling="oily">oily</palate>
            <palate type="feeling" feeling="heavy">Heavy</palate>
            <palate type="flavour" flavour="green olive">Green olive</palate>
            <finish type="feeling" feeling="rich">Rich</finish>
            <finish type="last" last="long">Long</finish>
        </new_make>
        
        <vintage>
            <name>Gold</name>
            <abv>40%</abv>
            <nose type="flavour" flavour="baked white bread">baked white bread</nose>
            <nose type="flavour" flavour="almond butter">almond butter</nose>
            <nose type="flavour" flavour="hay"> hay</nose>
            <nose type="flavour" flavour="vanilla">vanilla</nose>
            <nose type="feeling" feeling="warm">warm</nose>
            <nose type="feeling" feeling="yeasty">yeasty freshness mixes</nose>
            <palate type="feeling" feeling="substance">There's substance behind the light</palate>
            <palate type="feeling" feeling="opennose"> "open" nose</palate>
            <palate type="feeling" feeling="oil">a thickness, tougue-clinging oils</palate>
            <palate type="flavour" flavour="lemon">a vibrant lemon note</palate>
            <palate type="flavour" flavour="sweets">boiled travel sweets</palate>
            <finish type="feeling" feeling="dry">Dry </finish>
            <finish type="feeling" feeling="malty">malty </finish>
            <conclusion>A lighter introduction to The Macallan but full of distillery character.</conclusion>
            <flavourcamp type="fruity and spicy">Fruity and Spicy</flavourcamp>
            <wherenext>Benromach 10yo</wherenext>
        </vintage>
        
        <vintage>
            <year>15YO</year>
            <oak type="fine">Fine oak</oak>
            <abv>43%</abv>
            <nose type="colour" colour="gold">gold</nose>
            
            <nose type="flavour" flavour = "orange peel">Orange peel</nose>
            <nose type="flavour" flavour = "melon">melon</nose>
            <nose type="flavour" flavour = "mango">mango</nose>
            <nose type="flavour" flavour = "vanilla pod">vanilla pod</nose>
            <nose type="flavour" flavour = "sawdust">sawdust</nose>
            <nose type="flavour" flavour = "hazelnut">hazelnut</nose>
            <nose type="feeling" feeling ="polish">polish</nose>
            
            <palate type="flavour" flavour = "Nutty oak">nutty oak</palate>
            <palate type="flavour" flavour = "cooked orchard fruits">cooked orchard fruits</palate>
            <palate type="flavour" flavour = "black banana">black banana</palate>
            <palate type="flavour" flavour = "Caramel toffee">caramel toffee</palate>
            <palate type="flavour" flavour = "bracken">bracken</palate>
            <palate type="flavour" flavour = "malt">malt</palate>
            <palate type="flavour" flavour = "dark chocolate">dark chocolate</palate>
            
            <finish type="feeling" feeling = "complex">complex</finish>
            <finish type="feeling" feeling = "fruity">fruity</finish>
            
            <conclusion>The distillery character and "Fine Oak" casks in balance.</conclusion>
            <flavourcamp type="fruity and spicy">Fruity and Spicy</flavourcamp>
            <wherenext>Glenmorangie 18yo, Glencadam 15yo.</wherenext>
        </vintage>
        
        <vintage>
            <year>18YO</year>
            <oak type="sherry">Sherry oak</oak>
            <abv>43%</abv>
            <nose type="colour" colour="amber">Dark amber</nose>
            <nose type="flavour" flavour="fruit cake">Fruit cake</nose>
            <nose type="flavour" flavour="plum pudding">plum pudding</nose>
            <nose type="flavour" flavour="moist cake">rich moist cake</nose>
            <nose type="flavour" flavour="walnut">walnut</nose>
            <nose type="flavour" flavour="gingerbread">gingerbread</nose>
            <nose type="flavour" flavour="molasses">molasses</nose>
            <nose type="flavour" flavour="dried berries">dried berries</nose>
            <palate type="feeling" feeling="rich">rich</palate>
            <palate type="feeling" feeling="mouthfilling">mouthfilling</palate>
