=== FeiCoding/XML_Practice/Project1/dtd/stations.dtd
<!--The DTD file has a top element stations, which means there are several individual station elements-->
<!--Each station element has three main parts, which are image, name, information and history.                      -->
<!--The data type of station is required.                                                         -->

<!ELEMENT stations (station+)>
<!ELEMENT station (img, name, information, history)>
<!ATTLIST station type CDATA #REQUIRED>

<!--In image part, the image name and its source will be included. -->

<!ELEMENT img (imgName, imgSrc)>
<!ELEMENT imgName (#PCDATA)>
<!ELEMENT imgSrc (#PCDATA)>

<!--In name part, the current name of stations and its used name before will be present. -->
<!ELEMENT name (usedName*, currentName)>
<!ELEMENT usedName (#PCDATA)>
<!ELEMENT currentName (#PCDATA)>

<!--Information would include some more basic details about the station.-->
<!--Position must be included due to it's the most important information about the station, it should cover the position and postcode-->
<!--Open time need to cover the date, month and the year it opened. -->
<!--Zones is a hint to tell reader whether this station will make another cost due to the usage policy of underground-->
<!--Lines are another important information to tell reader whether it will cover some lines in the station -->
<!--The usage will tell the station how busy it is -->
<!ELEMENT information (position+, openedTime, zones, lines+, localAuthority+, usage, website)>
<!ELEMENT position (postcode, lineAdress)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT lineAdress (#PCDATA)>

<!ELEMENT openedTime (date*, month*, year)>
<!ELEMENT  date (#PCDATA)>
<!ELEMENT  month (#PCDATA)>
<!ELEMENT  year (#PCDATA)>

<!ELEMENT localAuthority (#PCDATA)>
<!ELEMENT zones (#PCDATA)>
<!ELEMENT lines (#PCDATA)>
<!ELEMENT usage (#PCDATA)>
<!ELEMENT website (#PCDATA)>

<!--History will be another important information for some reader to learn -->
<!--The body part contains many paragraphs -->
<!ELEMENT history (p+)>
<!ELEMENT p (#PCDATA| year_established )*>
<!ELEMENT year_established (#PCDATA)>

=== FeiCoding/XML_Practice/Project1/xml/NineElms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="building">
        <img>
            <imgName>NineElms</imgName>
            <imgSrc>https://en.wikipedia.org/wiki/List_of_London_Underground_stations#/media/File:Nine_Elms_London_Underground_Station_construction_site.jpg</imgSrc>
        </img>
        <name>
            <currentName>Nine Elms</currentName>
        </name>
        <information>
            <position>
                <postcode> SW8 4SR</postcode>
                <lineAdress> 52-, 58 Wandsworth Rd, London </lineAdress>
            </position>
            <openedTime> 
                <year>2020</year> 
            </openedTime>
            <zones> 1 </zones>
            <lines> Northern </lines>
            <localAuthority>Wandsworth</localAuthority>
            <usage> 0 </usage>
            <website>https://en.wikipedia.org/wiki/Nine_Elms_tube_station</website>
        </information>
        <history>
            <para>Nine Elms is a London Underground station under construction in Nine Elms, London, as part of the Northern line extension to Battersea. The station is projected to open along with the rest of the extension in 2020, and will serve the rapidly growing Nine Elms area, New Covent Garden Market and the new Embassy of the United States.</para>
            
                <para>The new station is close to the site of the former Nine Elms railway station, once the terminus of the London and South Western Railway.</para>
        </history>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/Queensway.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="">
        <img>
            <imgName>Queensway</imgName>
        </img>
        <name>
            <usedName>Queen's Road</usedName>
            <currentName>Queensway</currentName>
        </name>
        <information>
            <position>
                <postcode>W2 4RH</postcode>
                <lineAdress>Bayswater Rd, London </lineAdress>
            </position>
            <openedTime>
                <date>16</date>
                <month>July</month>
                <year>1900</year>
            </openedTime>
            <zones>1</zones>
            <lines>Central</lines>
            <usage>8.71</usage>
            <history>
                It opened on 30 July 1900, as Queen's Road, and was renamed on 1 September 1946. The building is an unusual survivor of the buildings designed for the Central London Railway by Harry Bell Measures, with a flat roof so that commercial development could take place above â€“ in this case, a hotel.
            </history>
        </information>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/NineElms.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="building">
        <img>
            <imgName>NineElms</imgName>
        </img>
        <name>
            <currentName>Nine Elms</currentName>
        </name>
        <information>
            <position>
                <postcode> SW8 4SR</postcode>
                <lineAdress> 52-, 58 Wandsworth Rd, London </lineAdress>
            </position>
            <openedTime> 
                <year>2020</year> 
            </openedTime>
            <zones> 1 </zones>
            <lines> Northern </lines>
            <usage> 0 </usage>
            <history>
                Nine Elms is a London Underground station under construction in Nine Elms, London, as part of the Northern line extension to Battersea. The station is projected to open along with the rest of the extension in 2020, and will serve the rapidly growing Nine Elms area, New Covent Garden Market and the new Embassy of the United States.
                
                The new station is close to the site of the former Nine Elms railway station, once the terminus of the London and South Western Railway.
            </history>
        </information>
    </station>
</stations>
