=== FeiCoding/XML_Practice/Project1/dtd/stations.dtd
<!--The DTD file has a top element stations, which means there are several individual station elements-->
<!--Each station element has three main parts, which are image, name, information and history.                      -->
<!--The data type of station is required.                                                         -->

<!ELEMENT stations (station+)>
<!ELEMENT station (img, name, information, history)>
<!ATTLIST station type CDATA #REQUIRED>

<!--In image part, the image name and its source will be included. -->

<!ELEMENT img (imgName, imgSrc)>
<!ELEMENT imgName (#PCDATA)>
<!ELEMENT imgSrc (#PCDATA)>

<!--In name part, the current name of stations and its used name before will be present. -->
<!ELEMENT name (usedName*, currentName)>
<!ELEMENT usedName (#PCDATA)>
<!ELEMENT currentName (#PCDATA)>

<!--Information would include some more basic details about the station.-->
<!--Position must be included due to it's the most important information about the station, it should cover the position and postcode-->
<!--Open time need to cover the date, month and the year it opened. -->
<!--Zones is a hint to tell reader whether this station will make another cost due to the usage policy of underground-->
<!--Lines are another important information to tell reader whether it will cover some lines in the station -->
<!--The usage will tell the station how busy it is -->
<!ELEMENT information (position+, openedTime, zones, lines+, localAuthority+, usage, website)>
<!ELEMENT position (postcode, lineAdress)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT lineAdress (#PCDATA)>

<!ELEMENT openedTime (date*, month*, year)>
<!ELEMENT  date (#PCDATA)>
<!ELEMENT  month (#PCDATA)>
<!ELEMENT  year (#PCDATA)>

<!ELEMENT localAuthority (#PCDATA)>
<!ELEMENT zones (#PCDATA)>
<!ELEMENT lines (#PCDATA)>
<!ELEMENT usage (#PCDATA)>
<!ELEMENT website (#PCDATA)>

<!--History will be another important information for some reader to learn -->
<!--The body part contains many paragraphs -->
<!ELEMENT history (p+)>
<!ELEMENT p (#PCDATA| year_established )*>
<!ELEMENT year_established (#PCDATA)>

=== FeiCoding/XML_Practice/childXML/CharingCross.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="opened">
        <img>
            <imgName>CharingCross</imgName>
        </img>
        <name>
            <usedName>Strand</usedName>
            <currentName>Charing Cross</currentName>
        </name>
        <information>
            <position>
                <postcode> WC2N 6DX </postcode>
                <lineAdress>
                    Embankment Pl London
                </lineAdress>
            </position>
            <openedTime>
                <date>10 </date>
                <month>March</month>
                <year>1906</year>
            </openedTime>
            <zones>1</zones>
            <lines>Bakerloo</lines>
            <lines>Northern</lines>
            <usage>8.13</usage>
            <history>
                The Northern line and Bakerloo line parts of the station were originally opened as two separate stations and were combined when the now defunct Jubilee line platforms were opened. The constituent stations also underwent a number of name changes during their history.
                
                The first part of the complex, the Bakerloo line platforms, was opened as Trafalgar Square by the Baker Street &amp; Waterloo Railway (BS&amp;WR) on 10 March 1906. The Northern line platforms were opened a year later, as Charing Cross, by the Charing Cross, Euston &amp; Hampstead Railway (CCE&amp;HR, now the Charing Cross branch of the Northern line) on 22 June 1907. At its opening this station was the southern terminus of the CCE&amp;HR which ran to two northern termini at Golders Green and Highgate (now Archway) tube stations.
                
                Although both lines were owned and operated by the Underground Electric Railways Company of London (UERL), there was no direct connection below ground and passengers interchanging between the lines had to do so via two sets of lifts and the surface. In an effort to improve interchange capabilities, the CCE&amp;HR was extended the short distance south under Charing Cross main line station to connect with the BS&amp;WR and the District Railway (another UERL line), opening as such on 6 April 1914.
            </history>
        </information>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/Amersham.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="opened">
        <img>
            <imgName>Amersham</imgName>
        </img>
        <name>
            <usedName>Amersham &amp; Chesham Bois</usedName>
            <currentName>Amersham</currentName>
        </name>
        <information>
            <position>
                <postcode>HP6 5AZ</postcode>
                <lineAdress>Amersham</lineAdress>
            </position>
            <openedTime>
                <date>9</date>
                <month>September</month>
                <year>1892</year>
            </openedTime>
            <zones>9</zones>
            <lines>Metropolitan</lines>
            <usage>2.36</usage>
            <history>
                The station was opened on 1 September 1892 as part of the Metropolitan Railway (Met) extension from Chalfont Road (now Chalfont &amp; Latimer) to Aylesbury. On 12 March 1922, its name was changed to "Amersham &amp; Chesham Bois", but the original name was restored during 1937.
                
                From 16 March 1899, the Great Central Railway served the station through its extension to Marylebone. Consequently, the station became joint Met/GCR owned. On 1 January 1923, the GCR became part of the London and North Eastern Railway (LNER) as part of the Railways Act 1921, and on 1 July 1933, the Met became part of the London Passenger Transport Board (LPTB), thus becoming the Metropolitan line of the London Underground. On 1 January 1948, the LNER was nationalised, its share of the station initially coming under the control of the Eastern Region of British Railways, before being transferred to the London Midland Region in 1958.
                
                On 12 September 1960, the tracks from Rickmansworth to Amersham were electrified, partially fulfilling plans first proposed some thirty years earlier. The rolling stock ordered by London Underground as part of this project, the A60 stock, is named after Amersham.
            </history>
        </information>
    </station>
</stations>

=== FeiCoding/XML_Practice/xml/Queensway.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="">
        <img>
            <imgName>Queensway</imgName>
            <imgSrc>https://en.wikipedia.org/wiki/List_of_London_Underground_stations#/media/File:Queensway_tube_station.jpg</imgSrc>
        </img>
        <name>
            <usedName>Queen's Road</usedName>
            <currentName>Queensway</currentName>
        </name>
        <information>
            <position>
                <postcode>W2 4RH</postcode>
                <lineAdress>Bayswater Rd, London </lineAdress>
            </position>
            <openedTime>
                <date>16</date>
                <month>July</month>
                <year>1900</year>
            </openedTime>
            <zones>1</zones>
            <lines>Central</lines>
            <localAuthority>City of Westminster</localAuthority>
            <usage>8.71</usage>
            <website>https://en.wikipedia.org/wiki/Queensway_tube_station</website>
        </information>
        <history>
            <para>It opened on 30 July 1900, as Queen's Road, and was renamed on 1 September 1946. The building is an unusual survivor of the buildings designed for the Central London Railway by Harry Bell Measures, with a flat roof so that commercial development could take place above â€“ in this case, a hotel.</para>
        </history>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/Waterloo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="opened">
        <img>
            <imgName>Waterloo</imgName>
        </img>
        <name>
            <currentName>Waterloo</currentName>
        </name>
        <information>
            <position>
                <postcode>
                    SE1 8SR
                </postcode>
                <lineAdress>South Bank, London</lineAdress>
            </position>
            <openedTime>
                <date>1</date>
                <month>March</month>
                <year>1906</year>
            </openedTime>
            <zones>1</zones>
            <lines>Waterloo &amp; City</lines>
            <lines>Bakerloo</lines>
            <lines>Northern</lines>
            <lines>Jubilee</lines>
            <usage>100.36</usage>
            <history>
                The first Underground Line at Waterloo was opened on 8 August 1898 by the Waterloo &amp; City Railway (W&amp;CR), a subsidiary of the owners of the main line station, the London and South Western Railway (L&amp;SWR). The W&amp;CR, nicknamed "The Drain", achieved in a limited way the L&amp;SWR's original plan of taking its tracks the short distance north-east into the City of London.
                
                On 10 March 1906, the Baker Street &amp; Waterloo Railway (BS&amp;WR, now the Bakerloo line) was opened. On 13 September 1926, the extension of the Hampstead &amp; Highgate line (as the Charing Cross branch of the Northern line was then known) was opened from Embankment to the existing City &amp; South London Railway station Kennington with a new station at Waterloo.
                
                As a subsidiary of the L&amp;SWR and its successor, the Southern Railway, the W&amp;CR was not a part of the London Underground system. Following nationalisation of the main line railway companies in 1948, it became part of British Railways (later British Rail).
                
                In March 1965, a British Rail and London Transport joint planning committee published "A Railway Plan for London" that included a recommendation to revive a plan from the 1900s for an extension of the Piccadilly line's Aldwych branch to Waterloo. London Transport had already sought parliamentary approval to construct tunnels from Aldwych to Waterloo in November 1964, and in August 1965, parliamentary powers were granted. Detailed planning took place, although public spending cuts led to postponement of the scheme in 1967 before tenders were invited.
                
                Following a period of closure during 1993 when the Waterloo &amp; City line was converted to use the four rail electrical system of the London Underground, the ownership of the line was transferred to the Underground on 1 April 1994. Due to an Easter shut-down, the first Underground service on the line was on 5 April 1994.
                
                On 24 September 1999, the Jubilee line platforms were opened as part of the Jubilee Line Extension. The station was temporarily the western terminus of the extension running from Stratford in east London, before the final section to link the extension to the original line was opened between Waterloo and Green Park on 20 November 1999. The Jubilee line platforms are at the opposite end of the site from those of the Bakerloo and Northern lines, but the two ends are connected by a 140-metre (460 ft) moving walkway link (one of only two on the Underground; the other gives access to the Waterloo &amp;amp; City line platform at Bank station).
            </history>
        </information>
    </station>
</stations>

=== FeiCoding/XML_Practice/xml/WoodLane.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="opened">
        <img>
            <imgName>WoodLane</imgName>
            <imgSrc>https://en.wikipedia.org/wiki/List_of_London_Underground_stations#/media/File:Wood_Lane_stn_entrance.JPG</imgSrc>
        </img>
        <name>
            <currentName> Wood Lane </currentName>
        </name>
        <information>
            <position>
                <postcode> W12 7SL </postcode>
                <lineAdress> Ariel Way, Shepherd's Bush, London</lineAdress>
            </position>
            <openedTime> 
                <date> 12 </date>
                <month> October </month>
                <year> 2008 </year>
            </openedTime>
            <zones> 2 </zones>
            <lines> Hammersmith &amp; City </lines>
            <lines> Circle </lines>
            <localAuthority>Hammersmith and Fulham</localAuthority>
            <usage> 3.68 </usage>
            <website>https://en.wikipedia.org/wiki/Wood_Lane_tube_station</website>
        </information>
        <history>
            <para>The Hammersmith and City line was opened on 13 June 1864 by the Metropolitan Railway (MR) as the Hammersmith branch line. The railway became part of London Underground in 1933 and the took on a separate identity as the Hammersmith and City line in 1988.</para>
            
            <para>In 1908 the Franco-British Exhibition and the 1908 Summer Olympics came to London, the first of a number of major events in White City that attracted infrastructural investment by railway companies. Among others, the MR opened its Wood Lane station on the Hammersmith branch to serve the event. From 1927 it was used to transport the public to and from the greyhound racing at White City Stadium. The station opened and closed intermittently, and was renamed twice, to Wood Lane (White City) in 1920 and White City in 1947, before it closed in 1959 following fire damage. For the next 49 years, the Wood Lane area was served only by White City on the Central line; Hammersmith line trains passed over the lane without stopping, the nearest station on that line approximately 1 km (0.62 mi) away at Shepherd's Bush.</para>
            
            <para>In 2005 work commenced on the large-scale Westfield Shopping Centre. As part of the work, improvements were made to public transport including rebuilding Shepherd's Bush Central line station, a new Shepherd's Bush railway station and two bus interchanges. It was decided to build a new station on the Hammersmith &amp; City line, just south-west of the old Metropolitan station on Wood Lane. In 2006 Transport for London decided on the name Wood Lane, reviving a historical name. This was the first time that a new station on the Tube had been given the name of a former station that had been closed for several years.</para>
            
            <para>The station opened on 12 October 2008. In December 2009 Wood Lane was added to the Circle line when the line was extended to Hammersmith.</para>
        </history>
    </station>
</stations>

=== FeiCoding/XML_Practice/xml/BakerStreet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="opened">
        <img>
            <imgName>BakerStreet</imgName>
            <imgSrc>https://en.wikipedia.org/wiki/List_of_London_Underground_stations#/media/File:BakerStEntrance.JPG</imgSrc>
        </img>
        <name>
            <currentName> Baker Street </currentName>
        </name>
        <information>
            <position>
                <postcode> HA3 8NT </postcode>
                <lineAdress> Marylebone Rd, Marylebone </lineAdress>
            </position>
            <openedTime> 
                <date> 10 </date>
                <month> January </month>
                <year> 1863 </year>
            </openedTime>
            <zones> 1 </zones>
            <lines> Metropolitan </lines>
            <lines> Bakerloo </lines>
            <lines> Circle </lines>
            <lines> Jubilee </lines>
            <lines>Hammersmith &amp; City </lines>
            <localAuthority>City of Westminster</localAuthority>
            <usage> 29.75 </usage>
            <website>https://en.wikipedia.org/wiki/Baker_Street_tube_station</website>
        </information>
        <history> 
            <para>In the first half of the 19th century, the population and physical extent of London grew greatly. The congested streets and the distance to the City from the stations to the north and west prompted many attempts to get parliamentary approval to build new railway lines into the City. In 1852, Charles Pearson planned a railway from Farringdon to King's Cross. Although the plan was supported by the City, the railway companies were not interested and the company struggled to proceed. The Bayswater, Paddington, and Holborn Bridge Railway Company was established to connect the Great Western Railway's (GWR) Paddington station to Pearson's route at King's Cross. A bill was published in November 1852 and in January 1853 the directors held their first meeting and appointed John Fowler as its engineer. Several bills were submitted for a route between Paddington and Farringdon.The company's name was also to be changed again, to Metropolitan Railway and the route was approved on 7 August 1854.</para>
            
            <para>Construction began in March 1860 with works mostly using the "cut-and-cover" method from Paddington to King's Cross; east of there it continued in a short tunnel then followed the culverted River Fleet in an open cutting to near the new Smithfield meat market. Delayed by several accidents during construction, work was complete by the end of 1862 at a cost of Â£1.3 million. The railway opened to the public on Saturday 10 January 1863. The Met was granted permission for two additional tracks (the City Widened Lines) from King's Cross to Farringdon Street in 1861, and a four-track eastward extension to Moorgate in 1864. The extension to Aldersgate Street and Moorgate Street (now Barbican and Moorgate) opened on 23 December 1865. On 13 April 1868, the MR opened the first section of Metropolitan and St John's Wood Railway as a branch from its existing route. This line, serving the open-air platforms, was steadily extended to Willesden Green and northwards, finally reaching Aylesbury Town and Verney Junction (some 50 miles/80 km from Baker Street) in 1892. The MR station mainly competed for traffic with Euston, where the LNWR provided local services to Middlesex and Watford, and later with Marylebone, where the GCR provided expresses to Aylesbury and beyond on the same line.</para>
            
                <para>Over the next few decades this section of the station was extensively rebuilt to provide four platforms. The current Metropolitan line layout largely dates from 1925, and the bulk of the surface buildings, designed by architect Charles Walter Clark, also date from this period.</para>
            
                <para>As part of the Transported by Design programme of activities, in 15 October 2015, after two months of public voting, Baker Street underground station's platforms were elected by Londoners as one of the 10 favourite transport design icons.</para>
        </history>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/Cassiobridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="building">
        <img>
            <imgName>Cassiobridge</imgName>
        </img>
        <name>
            <currentName>Cassiobridge</currentName>
        </name>
        <information>
            <position>
                <postcode>WD18 7QQ</postcode>
                <lineAdress>Cassiobridge Road</lineAdress>
            </position>
            <openedTime>
                <year>2020</year>
            </openedTime>
            <zones>7</zones>
            <lines>Metropolitan</lines>
            <usage>0</usage>
            <history>
                Cassiobridge is a proposed London Underground station in Watford, Hertfordshire, England. The station would be part of the Croxley Rail Link project, a scheme to extend the Metropolitan line to Watford Junction railway station. It would be served by Metropolitan line trains between Watford Junction and Central London via Baker Street. The railway line would run over Ascot Road via a viaduct and the platforms will be situated on the east side of the road. Entrance to the station would be from the west side of the road, with a ticket hall and other facilities at street level. Passengers would gain access to the platforms via stairs and lifts and a short footbridge over the road.
                
                The station is projected to offer interchange with local transport services, and operate as an unstaffed station, providing automatic ticketing facilities similar to a DLR station. There is potential for Park and Ride facilities to be provided, although planning documents indicate high levels of congestion on adjacent roads.
                
                After the new line is opened Watford station will be closed to passenger services, so that all trains from Croxley will continue to Watford Junction. Cassiobridge also replaces the disused British Rail terminus of Croxley Green.
                
                The railway and station were expected to come into service in 2020. On 25 January 2017, the Watford Observer newspaper published an update on the Croxley Rail Link confirming work had stopped as there was an ongoing funding issue.
            </history>
        </information>
    </station>
</stations>

=== FeiCoding/XML_Practice/childXML/Euston.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE stations SYSTEM "stations.dtd">
<stations>
    <station type="">
        <img>
            <imgName>Euston</imgName>
        </img>
        <name>
            <currentName>Euston</currentName>
        </name>
        <information>
            <position>
                <postcode> NW1 2DU </postcode>
                <lineAdress>
                    Euston Station
                    Kings Cross, London
                </lineAdress>
            </position>
            <openedTime>
                <date> 22 </date>
                <month> June </month>
                <year> 1907 </year>
            </openedTime>
            <zones>1</zones>
            <lines>Northern</lines>
            <lines>Victoria</lines>
            <usage>43.10</usage>
            <history>
                Most of the C&amp;SLR's route had been constructed with tunnels 10 feet 2 inches (3.10 m) or 10 feet 6 inches (3.20 m) in diameter, smaller than the 11 feet 6 inches (3.51 m) diameter that had been adopted as the standard for the CCE&amp;HR and other deep level tube lines. The smaller tunnel size restricted the capacity of the C&amp;SLR's trains and, in 1912, the C&amp;SLR published a bill for their enlargement. A separate bill was published at the same time by the London Electric Railway (LER), that included plans to construct tunnels to connect the C&amp;SLR at Euston to the CCE&amp;HR's station at Camden Town. Together, the works proposed in these bills would enable trains of each company to run over the route of the other, effectively combining the two separate railways. The reconstruction and extension works were postponed during World War I and did not begin until 1922. The C&amp;SLR platforms and the tunnels between Euston and Moorgate were closed for the reconstruction on 8 August 1922. They reopened on 20 April 1924 along with the new link to Camden Town.
            </history>
        </information>
    </station>
</stations>
